name: Update counters

on:
  schedule:
    - cron: "0 * * * *"   # Ñ€Ð°Ð· Ð² Ñ‡Ð°Ñ (Ð¼Ð¾Ð¶Ð½Ð¾ Ñ€ÐµÐ¶Ðµ)
  workflow_dispatch:       # Ð·Ð°Ð¿ÑƒÑÐº Ð²Ñ€ÑƒÑ‡Ð½ÑƒÑŽ

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Count repos
        env:
          GH_TOKEN: ${{ github.token }}
          USERNAME: GuitarEmo 
        run: |
          set -e
          headers="-H 'Authorization: Bearer $GH_TOKEN' -H 'Accept: application/vnd.github+json'"

          JOBS=$(curl -s https://api.github.com/search/repositories?q=user:$USERNAME+in:name+job $headers | jq -r .total_count)
          POSTS=$(curl -s https://api.github.com/search/repositories?q=user:$USERNAME+in:name+post $headers | jq -r .total_count)

          mkdir -p badges

          cat > badges/job-count.json <<JSON
          { "schemaVersion": 1, "label": "ðŸ’¼ ÐžÑ‚ÐºÑ€Ñ‹Ñ‚Ñ‹Ðµ Ð²Ð°ÐºÐ°Ð½ÑÐ¸Ð¸", "message": "${JOBS}", "color": "00D0BF" }
          JSON

          cat > badges/post-count.json <<JSON
          { "schemaVersion": 1, "label": "ðŸ“ ÐŸÐ¾Ð»ÐµÐ·Ð½Ñ‹Ðµ Ð¿Ð¾ÑÑ‚Ñ‹", "message": "${POSTS}", "color": "00D0BF" }
          JSON

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/*.json
          git commit -m "update counters" || echo "No changes"
          git push
